/*
 * КАТАЛОГ ТОВАРОВ
 * ----------------
 * Каталог собран из Telegram-канала скриптом tools/import_telegram.py.
 * Его можно править и вручную. Поля товара:
 *   id          — внутренний номер (может меняться при импорте)
 *   lot         — номер лота, который видят покупатели. Не меняется:
 *                 новые изделия получают следующий свободный номер
 *   tg          — номер поста в Telegram-канале (по нему скрипт
 *                 сохраняет лоты и цены при повторном импорте)
 *   name        — название
 *   category    — одна из категорий из списка CATEGORIES ниже
 *   price       — цена в сумах (число, без пробелов), например 3500000.
 *                 Пока цена не вписана (null), на сайте будет «Цена по запросу».
 *   oldPrice    — старая цена для скидки (необязательно)
 *   material    — металл и проба
 *   weight      — вес в граммах (необязательно), например 5.5
 *   stones      — камни (необязательно)
 *   description — описание (необязательно)
 *   images      — фотографии; первая показывается в каталоге
 *   isNew       — true, если нужно показать метку «Новинка» (необязательно)
 *   inStock     — false, если товара нет в наличии (необязательно)
 *   uz, kaa     — перевод на узбекский и каракалпакский: name, material,
 *                 stones, description. Если перевода нет, покажется русский текст.
 */

// Категории: ключ — латиницей, затем название на русском и узбекском
const CATEGORIES = {
  sets: { ru: "Комплекты", uz: "To'plamlar", kaa: "Komplektler" },
  earrings: { ru: "Серьги", uz: "Sirg'alar", kaa: "Sırǵalar" },
  rings: { ru: "Кольца", uz: "Uzuklar", kaa: "Júzikler" },
  wedding: { ru: "Обручальные кольца", uz: "Nikoh uzuklari", kaa: "Neke júzikleri" },
  men: { ru: "Мужские перстни", uz: "Erkaklar uzuklari", kaa: "Erler júzikleri" },
  pendants: { ru: "Кулоны", uz: "Kulonlar", kaa: "Kulonlar" },
  chains: { ru: "Цепочки и браслеты", uz: "Zanjir va bilaguzuklar", kaa: "Shınjır hám bilezikler" },
  watches: { ru: "Часы", uz: "Soatlar", kaa: "Saatlar" },
};

const PRODUCTS = [
  {
    id: 1,
    lot: 150,
    tg: 631,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото",
    weight: 6.8,
    stones: "Бриллианты",
    images: ["images/products/tg-631-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "Oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "Altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 2,
    lot: 149,
    tg: 630,
    name: "Цепочка",
    category: "chains",
    price: null,
    material: "Золото",
    weight: 1.7,
    images: ["images/products/tg-630-1.jpg"],
    uz: {
      name: "Zanjir",
      material: "Oltin",
    },
    kaa: {
      name: "Shınjır",
      material: "Altın",
    },
  },
  {
    id: 3,
    lot: 148,
    tg: 628,
    name: "Часы мужские",
    category: "watches",
    price: null,
    material: "Золото 583",
    weight: 58.2,
    images: ["images/products/tg-628-1.jpg"],
    uz: {
      name: "Erkaklar soati",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Erler saatı",
      material: "583 probalı altın",
    },
  },
  {
    id: 4,
    lot: 147,
    tg: 627,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото",
    weight: 5.1,
    stones: "Бриллианты",
    images: ["images/products/tg-627-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "Oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "Altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 5,
    lot: 146,
    tg: 626,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 14.8,
    stones: "Бриллианты",
    images: ["images/products/tg-626-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 6,
    lot: 145,
    tg: 625,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото",
    images: ["images/products/tg-625-1.jpg"],
    uz: {
      name: "Kulon",
      material: "Oltin",
    },
    kaa: {
      name: "Kulon",
      material: "Altın",
    },
  },
  {
    id: 7,
    lot: 144,
    tg: 624,
    name: "Серьги «Союз»",
    category: "earrings",
    price: null,
    material: "Золото",
    weight: 6.5,
    images: ["images/products/tg-624-1.jpg"],
    uz: {
      name: "Sirg'alar «Союз»",
      material: "Oltin",
    },
    kaa: {
      name: "Sırǵalar «Союз»",
      material: "Altın",
    },
  },
  {
    id: 8,
    lot: 143,
    tg: 623,
    name: "Комплект «Союз»",
    category: "sets",
    price: null,
    material: "Золото",
    weight: 7.5,
    images: ["images/products/tg-623-1.jpg"],
    uz: {
      name: "To'plam «Союз»",
      material: "Oltin",
    },
    kaa: {
      name: "Komplekt «Союз»",
      material: "Altın",
    },
  },
  {
    id: 9,
    lot: 142,
    tg: 621,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото",
    weight: 5.2,
    stones: "Бриллианты",
    images: ["images/products/tg-621-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "Oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "Altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 10,
    lot: 141,
    tg: 620,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото",
    weight: 7.2,
    stones: "Бриллианты",
    images: ["images/products/tg-620-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "Oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "Altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 11,
    lot: 140,
    tg: 613,
    name: "Серьги «Союз»",
    category: "earrings",
    price: null,
    material: "Золото",
    weight: 11.0,
    images: ["images/products/tg-613-1.jpg"],
    uz: {
      name: "Sirg'alar «Союз»",
      material: "Oltin",
    },
    kaa: {
      name: "Sırǵalar «Союз»",
      material: "Altın",
    },
  },
  {
    id: 12,
    lot: 139,
    tg: 612,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 750",
    stones: "Бриллианты",
    images: ["images/products/tg-612-1.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "750 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Sırǵalar",
      material: "750 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 13,
    lot: 138,
    tg: 609,
    name: "Серьги «Союз»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 7.7,
    images: ["images/products/tg-609-1.jpg"],
    uz: {
      name: "Sirg'alar «Союз»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Союз»",
      material: "583 probalı altın",
    },
  },
  {
    id: 14,
    lot: 137,
    tg: 608,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото",
    weight: 5.9,
    stones: "Бриллианты",
    images: ["images/products/tg-608-1.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "Oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Sırǵalar",
      material: "Altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 15,
    lot: 136,
    tg: 607,
    name: "Браслет",
    category: "chains",
    price: null,
    material: "Золото",
    weight: 9.75,
    images: ["images/products/tg-607-1.jpg"],
    uz: {
      name: "Bilaguzuk",
      material: "Oltin",
    },
    kaa: {
      name: "Bilezik",
      material: "Altın",
    },
  },
  {
    id: 16,
    lot: 135,
    tg: 602,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 583",
    stones: "Бриллианты",
    images: ["images/products/tg-602-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 17,
    lot: 134,
    tg: 568,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 750",
    stones: "Бриллианты",
    images: ["images/products/tg-568-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "750 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "750 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 18,
    lot: 133,
    tg: 567,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 750",
    stones: "Бриллианты",
    images: ["images/products/tg-567-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "750 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "750 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 19,
    lot: 132,
    tg: 548,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 9.5,
    stones: "Бриллианты",
    images: ["images/products/tg-548-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 20,
    lot: 131,
    tg: 547,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 9.8,
    stones: "Бриллианты",
    images: ["images/products/tg-547-1.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 21,
    lot: 130,
    tg: 546,
    name: "Комплект",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 17.0,
    images: ["images/products/tg-546-1.jpg"],
    uz: {
      name: "To'plam",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Komplekt",
      material: "583 probalı altın",
    },
  },
  {
    id: 22,
    lot: 129,
    tg: 372,
    name: "Серьги «Бирюза»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 1.5,
    stones: "Бирюза",
    images: ["images/products/tg-372-1.jpg", "images/products/tg-372-2.jpg"],
    uz: {
      name: "Sirg'alar «Бирюза»",
      material: "583 probali oltin",
      stones: "Feruza",
    },
    kaa: {
      name: "Sırǵalar «Бирюза»",
      material: "583 probalı altın",
      stones: "Piruza",
    },
  },
  {
    id: 23,
    lot: 128,
    tg: 370,
    name: "Серьги «Бадам»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 6.5,
    stones: "Бриллианты",
    images: ["images/products/tg-370-1.jpg", "images/products/tg-370-2.jpg"],
    uz: {
      name: "Sirg'alar «Бадам»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Sırǵalar «Бадам»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 24,
    lot: 127,
    tg: 368,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 9.0,
    stones: "Бриллианты",
    images: ["images/products/tg-368-1.jpg", "images/products/tg-368-2.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 25,
    lot: 126,
    tg: 366,
    name: "Комплект с бриллиантами «Бахча сарай»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 7.6,
    stones: "Бриллианты",
    images: ["images/products/tg-366-1.jpg", "images/products/tg-366-2.jpg"],
    uz: {
      name: "Brilliantli to'plam «Бахча сарай»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Бахча сарай»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 26,
    lot: 125,
    tg: 364,
    name: "Комплект с бриллиантами «Ромашка»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 7.3,
    stones: "Бриллианты",
    images: ["images/products/tg-364-1.jpg", "images/products/tg-364-2.jpg"],
    uz: {
      name: "Brilliantli to'plam «Ромашка»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Ромашка»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 27,
    lot: 124,
    tg: 362,
    name: "Кольцо «Сказка»",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 4.7,
    stones: "Бриллианты",
    images: ["images/products/tg-362-1.jpg", "images/products/tg-362-2.jpg"],
    uz: {
      name: "Uzuk «Сказка»",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Júzik «Сказка»",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 28,
    lot: 123,
    tg: 360,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 4.6,
    stones: "Бриллианты, изумруд",
    images: ["images/products/tg-360-1.jpg", "images/products/tg-360-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
      stones: "Brilliantlar, zumrad",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
      stones: "Brilliantlar, zúmirat",
    },
  },
  {
    id: 29,
    lot: 122,
    tg: 353,
    name: "Мужской перстень",
    category: "men",
    price: null,
    material: "Золото 585",
    weight: 5.9,
    images: ["images/products/tg-353-1.jpg", "images/products/tg-353-2.jpg"],
    uz: {
      name: "Erkaklar uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Erler júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 30,
    lot: 121,
    tg: 351,
    name: "Мужской перстень",
    category: "men",
    price: null,
    material: "Золото 585",
    weight: 2.8,
    images: ["images/products/tg-351-1.jpg", "images/products/tg-351-2.jpg"],
    uz: {
      name: "Erkaklar uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Erler júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 31,
    lot: 120,
    tg: 349,
    name: "Мужской перстень",
    category: "men",
    price: null,
    material: "Золото 583",
    weight: 7.1,
    images: ["images/products/tg-349-1.jpg", "images/products/tg-349-2.jpg"],
    uz: {
      name: "Erkaklar uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Erler júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 32,
    lot: 119,
    tg: 347,
    name: "Мужской перстень",
    category: "men",
    price: null,
    material: "Золото 585",
    weight: 9.78,
    images: ["images/products/tg-347-1.jpg", "images/products/tg-347-2.jpg"],
    uz: {
      name: "Erkaklar uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Erler júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 33,
    lot: 118,
    tg: 345,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 585",
    weight: 2.6,
    images: ["images/products/tg-345-1.jpg", "images/products/tg-345-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 34,
    lot: 117,
    tg: 343,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 585",
    weight: 2.7,
    images: ["images/products/tg-343-1.jpg", "images/products/tg-343-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 35,
    lot: 116,
    tg: 341,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 2.7,
    images: ["images/products/tg-341-1.jpg", "images/products/tg-341-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 36,
    lot: 115,
    tg: 339,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 1.65,
    images: ["images/products/tg-339-1.jpg", "images/products/tg-339-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 37,
    lot: 114,
    tg: 337,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 2.75,
    images: ["images/products/tg-337-1.jpg", "images/products/tg-337-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 38,
    lot: 113,
    tg: 335,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 5.3,
    images: ["images/products/tg-335-1.jpg", "images/products/tg-335-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 39,
    lot: 112,
    tg: 333,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 585",
    weight: 2.62,
    images: ["images/products/tg-333-1.jpg", "images/products/tg-333-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 40,
    lot: 111,
    tg: 331,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 5.05,
    images: ["images/products/tg-331-1.jpg", "images/products/tg-331-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 41,
    lot: 110,
    tg: 329,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 585",
    weight: 2.05,
    images: ["images/products/tg-329-1.jpg", "images/products/tg-329-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 42,
    lot: 109,
    tg: 327,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 585",
    weight: 3.65,
    images: ["images/products/tg-327-1.jpg", "images/products/tg-327-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "585 probalı altın",
    },
  },
  {
    id: 43,
    lot: 108,
    tg: 325,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 5.05,
    images: ["images/products/tg-325-1.jpg", "images/products/tg-325-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 44,
    lot: 107,
    tg: 323,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 3.72,
    images: ["images/products/tg-323-1.jpg", "images/products/tg-323-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 45,
    lot: 106,
    tg: 321,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 3.2,
    images: ["images/products/tg-321-1.jpg", "images/products/tg-321-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 46,
    lot: 105,
    tg: 319,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 6.0,
    images: ["images/products/tg-319-1.jpg", "images/products/tg-319-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 47,
    lot: 104,
    tg: 317,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 2.35,
    images: ["images/products/tg-317-1.jpg", "images/products/tg-317-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 48,
    lot: 103,
    tg: 315,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 3.52,
    images: ["images/products/tg-315-1.jpg", "images/products/tg-315-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 49,
    lot: 102,
    tg: 313,
    name: "Обручальное кольцо",
    category: "wedding",
    price: null,
    material: "Золото 583",
    weight: 5.5,
    images: ["images/products/tg-313-1.jpg", "images/products/tg-313-2.jpg"],
    uz: {
      name: "Nikoh uzugi",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Neke júzigi",
      material: "583 probalı altın",
    },
  },
  {
    id: 50,
    lot: 101,
    tg: 311,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 4.9,
    images: ["images/products/tg-311-1.jpg", "images/products/tg-311-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 51,
    lot: 100,
    tg: 309,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 3.55,
    stones: "Бриллианты",
    images: ["images/products/tg-309-1.jpg", "images/products/tg-309-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 52,
    lot: 99,
    tg: 307,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 4.55,
    images: ["images/products/tg-307-1.jpg", "images/products/tg-307-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 53,
    lot: 98,
    tg: 305,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 4.6,
    stones: "Бриллианты",
    images: ["images/products/tg-305-1.jpg", "images/products/tg-305-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 54,
    lot: 97,
    tg: 303,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 3.0,
    images: ["images/products/tg-303-1.jpg", "images/products/tg-303-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
    },
  },
  {
    id: 55,
    lot: 96,
    tg: 301,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 4.8,
    images: ["images/products/tg-301-1.jpg", "images/products/tg-301-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 56,
    lot: 95,
    tg: 299,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 2.65,
    stones: "Бриллианты",
    images: ["images/products/tg-299-1.jpg", "images/products/tg-299-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 57,
    lot: 94,
    tg: 297,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 7.2,
    images: ["images/products/tg-297-1.jpg", "images/products/tg-297-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 58,
    lot: 93,
    tg: 295,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 3.35,
    stones: "Бриллианты",
    images: ["images/products/tg-295-1.jpg", "images/products/tg-295-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 59,
    lot: 92,
    tg: 293,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 2.9,
    stones: "Бриллианты",
    images: ["images/products/tg-293-1.jpg", "images/products/tg-293-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 60,
    lot: 91,
    tg: 291,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 3.25,
    images: ["images/products/tg-291-1.jpg", "images/products/tg-291-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 61,
    lot: 90,
    tg: 289,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 2.95,
    images: ["images/products/tg-289-1.jpg", "images/products/tg-289-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 62,
    lot: 89,
    tg: 287,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 4.0,
    images: ["images/products/tg-287-1.jpg", "images/products/tg-287-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 63,
    lot: 88,
    tg: 285,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 6.4,
    images: ["images/products/tg-285-1.jpg", "images/products/tg-285-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 64,
    lot: 87,
    tg: 283,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 5.2,
    images: ["images/products/tg-283-1.jpg", "images/products/tg-283-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
    },
  },
  {
    id: 65,
    lot: 86,
    tg: 281,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 1.52,
    images: ["images/products/tg-281-1.jpg", "images/products/tg-281-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
    },
  },
  {
    id: 66,
    lot: 85,
    tg: 279,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 3.4,
    images: ["images/products/tg-279-1.jpg", "images/products/tg-279-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
    },
  },
  {
    id: 67,
    lot: 84,
    tg: 277,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 4.55,
    images: ["images/products/tg-277-1.jpg", "images/products/tg-277-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
    },
  },
  {
    id: 68,
    lot: 83,
    tg: 275,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 585",
    weight: 4.25,
    images: ["images/products/tg-275-1.jpg", "images/products/tg-275-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "585 probalı altın",
    },
  },
  {
    id: 69,
    lot: 82,
    tg: 273,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 6.35,
    images: ["images/products/tg-273-1.jpg", "images/products/tg-273-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 70,
    lot: 81,
    tg: 271,
    name: "Кольцо",
    category: "rings",
    price: null,
    material: "Золото 583",
    weight: 4.4,
    images: ["images/products/tg-271-1.jpg", "images/products/tg-271-2.jpg"],
    uz: {
      name: "Uzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Júzik",
      material: "583 probalı altın",
    },
  },
  {
    id: 71,
    lot: 80,
    tg: 269,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 585",
    weight: 4.25,
    images: ["images/products/tg-269-1.jpg", "images/products/tg-269-2.jpg"],
    uz: {
      name: "Kulon",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "585 probalı altın",
    },
  },
  {
    id: 72,
    lot: 79,
    tg: 266,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 585",
    weight: 3.0,
    images: ["images/products/tg-266-1.jpg", "images/products/tg-266-2.jpg"],
    uz: {
      name: "Kulon",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "585 probalı altın",
    },
  },
  {
    id: 73,
    lot: 78,
    tg: 264,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 585",
    weight: 1.25,
    images: ["images/products/tg-264-1.jpg", "images/products/tg-264-2.jpg"],
    uz: {
      name: "Kulon",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "585 probalı altın",
    },
  },
  {
    id: 74,
    lot: 77,
    tg: 262,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 750",
    weight: 3.75,
    images: ["images/products/tg-262-1.jpg", "images/products/tg-262-2.jpg"],
    uz: {
      name: "Kulon",
      material: "750 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "750 probalı altın",
    },
  },
  {
    id: 75,
    lot: 76,
    tg: 260,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 585",
    weight: 4.5,
    images: ["images/products/tg-260-1.jpg", "images/products/tg-260-2.jpg"],
    uz: {
      name: "Kulon",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "585 probalı altın",
    },
  },
  {
    id: 76,
    lot: 75,
    tg: 258,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 583",
    weight: 4.7,
    images: ["images/products/tg-258-1.jpg", "images/products/tg-258-2.jpg"],
    uz: {
      name: "Kulon",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "583 probalı altın",
    },
  },
  {
    id: 77,
    lot: 74,
    tg: 256,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 585",
    weight: 2.25,
    images: ["images/products/tg-256-1.jpg", "images/products/tg-256-2.jpg"],
    uz: {
      name: "Kulon",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "585 probalı altın",
    },
  },
  {
    id: 78,
    lot: 73,
    tg: 254,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 583",
    weight: 2.2,
    images: ["images/products/tg-254-1.jpg", "images/products/tg-254-2.jpg"],
    uz: {
      name: "Kulon",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "583 probalı altın",
    },
  },
  {
    id: 79,
    lot: 72,
    tg: 252,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 583",
    weight: 2.4,
    images: ["images/products/tg-252-1.jpg", "images/products/tg-252-2.jpg"],
    uz: {
      name: "Kulon",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "583 probalı altın",
    },
  },
  {
    id: 80,
    lot: 71,
    tg: 250,
    name: "Кулон",
    category: "pendants",
    price: null,
    material: "Золото 585",
    weight: 1.6,
    images: ["images/products/tg-250-1.jpg", "images/products/tg-250-2.jpg"],
    uz: {
      name: "Kulon",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Kulon",
      material: "585 probalı altın",
    },
  },
  {
    id: 81,
    lot: 70,
    tg: 247,
    name: "Браслет",
    category: "chains",
    price: null,
    material: "Золото 583",
    weight: 6.9,
    images: ["images/products/tg-247-1.jpg", "images/products/tg-247-2.jpg", "images/products/tg-247-3.jpg"],
    uz: {
      name: "Bilaguzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Bilezik",
      material: "583 probalı altın",
    },
  },
  {
    id: 82,
    lot: 69,
    tg: 244,
    name: "Браслет",
    category: "chains",
    price: null,
    material: "Золото 585",
    weight: 3.7,
    images: ["images/products/tg-244-1.jpg", "images/products/tg-244-2.jpg", "images/products/tg-244-3.jpg"],
    uz: {
      name: "Bilaguzuk",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Bilezik",
      material: "585 probalı altın",
    },
  },
  {
    id: 83,
    lot: 68,
    tg: 242,
    name: "Часы",
    category: "watches",
    price: null,
    material: "Золото 583",
    weight: 21.5,
    images: ["images/products/tg-242-1.jpg", "images/products/tg-242-2.jpg"],
    uz: {
      name: "Soat",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Saat",
      material: "583 probalı altın",
    },
  },
  {
    id: 84,
    lot: 67,
    tg: 240,
    name: "Цепочка «Мидас»",
    category: "chains",
    price: null,
    material: "Золото 585",
    weight: 8.6,
    images: ["images/products/tg-240-1.jpg", "images/products/tg-240-2.jpg"],
    uz: {
      name: "Zanjir «Мидас»",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Shınjır «Мидас»",
      material: "585 probalı altın",
    },
  },
  {
    id: 85,
    lot: 66,
    tg: 238,
    name: "Цепочка",
    category: "chains",
    price: null,
    material: "Золото 585",
    weight: 15.0,
    images: ["images/products/tg-238-1.jpg", "images/products/tg-238-2.jpg"],
    uz: {
      name: "Zanjir",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Shınjır",
      material: "585 probalı altın",
    },
  },
  {
    id: 86,
    lot: 65,
    tg: 236,
    name: "Цепочка «Колокольчик»",
    category: "chains",
    price: null,
    material: "Золото 583",
    weight: 24.5,
    images: ["images/products/tg-236-1.jpg", "images/products/tg-236-2.jpg"],
    uz: {
      name: "Zanjir «Колокольчик»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Shınjır «Колокольчик»",
      material: "583 probalı altın",
    },
  },
  {
    id: 87,
    lot: 64,
    tg: 233,
    name: "Браслет",
    category: "chains",
    price: null,
    material: "Золото 583",
    weight: 21.8,
    images: ["images/products/tg-233-1.jpg", "images/products/tg-233-2.jpg", "images/products/tg-233-3.jpg"],
    uz: {
      name: "Bilaguzuk",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Bilezik",
      material: "583 probalı altın",
    },
  },
  {
    id: 88,
    lot: 63,
    tg: 230,
    name: "Комплект с бриллиантами «Guldaste»",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 11.7,
    stones: "Бриллианты",
    images: ["images/products/tg-230-1.jpg", "images/products/tg-230-2.jpg", "images/products/tg-230-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Guldaste»",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Guldaste»",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 89,
    lot: 62,
    tg: 227,
    name: "Комплект с бриллиантами «Звёздочка»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.75,
    stones: "Бриллианты",
    images: ["images/products/tg-227-1.jpg", "images/products/tg-227-2.jpg", "images/products/tg-227-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Звёздочка»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Звёздочка»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 90,
    lot: 61,
    tg: 224,
    name: "Комплект с бриллиантами «Ткач»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.9,
    stones: "Бриллианты",
    images: ["images/products/tg-224-1.jpg", "images/products/tg-224-2.jpg", "images/products/tg-224-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Ткач»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Ткач»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 91,
    lot: 60,
    tg: 221,
    name: "Комплект с бриллиантами «Guldaste»",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 11.4,
    stones: "Бриллианты",
    images: ["images/products/tg-221-1.jpg", "images/products/tg-221-2.jpg", "images/products/tg-221-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Guldaste»",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Guldaste»",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 92,
    lot: 59,
    tg: 218,
    name: "Комплект с бриллиантами «Корона»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 10.35,
    stones: "Бриллианты",
    images: ["images/products/tg-218-1.jpg", "images/products/tg-218-2.jpg", "images/products/tg-218-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Корона»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Корона»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 93,
    lot: 58,
    tg: 215,
    name: "Комплект с бриллиантами «Бахча сарай»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 9.4,
    stones: "Бриллианты",
    images: ["images/products/tg-215-1.jpg", "images/products/tg-215-2.jpg", "images/products/tg-215-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Бахча сарай»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Бахча сарай»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 94,
    lot: 57,
    tg: 212,
    name: "Комплект с бриллиантами «Ободок»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.5,
    stones: "Бриллианты",
    images: ["images/products/tg-212-1.jpg", "images/products/tg-212-2.jpg", "images/products/tg-212-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Ободок»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Ободок»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 95,
    lot: 56,
    tg: 209,
    name: "Комплект с бриллиантами «Висячка»",
    category: "sets",
    price: null,
    material: "Золото 750",
    weight: 13.0,
    stones: "Бриллианты",
    images: ["images/products/tg-209-1.jpg", "images/products/tg-209-2.jpg", "images/products/tg-209-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Висячка»",
      material: "750 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Висячка»",
      material: "750 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 96,
    lot: 55,
    tg: 206,
    name: "Комплект с бриллиантами «Gulim»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 8.1,
    stones: "Бриллианты",
    images: ["images/products/tg-206-1.jpg", "images/products/tg-206-2.jpg", "images/products/tg-206-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Gulim»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Gulim»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 97,
    lot: 54,
    tg: 203,
    name: "Комплект с бриллиантами «Пламя»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 9.0,
    stones: "Бриллианты",
    images: ["images/products/tg-203-1.jpg", "images/products/tg-203-2.jpg", "images/products/tg-203-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Пламя»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Пламя»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 98,
    lot: 53,
    tg: 200,
    name: "Комплект с бриллиантами «Шахмат»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 8.15,
    stones: "Бриллианты",
    images: ["images/products/tg-200-1.jpg", "images/products/tg-200-2.jpg", "images/products/tg-200-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Шахмат»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Шахмат»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 99,
    lot: 52,
    tg: 197,
    name: "Комплект с бриллиантами «Ободок»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.5,
    stones: "Бриллианты",
    images: ["images/products/tg-197-1.jpg", "images/products/tg-197-2.jpg", "images/products/tg-197-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Ободок»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Ободок»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 100,
    lot: 51,
    tg: 194,
    name: "Комплект с бриллиантами «Тарелка»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 10.1,
    stones: "Бриллианты",
    images: ["images/products/tg-194-1.jpg", "images/products/tg-194-2.jpg", "images/products/tg-194-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Тарелка»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Тарелка»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 101,
    lot: 50,
    tg: 191,
    name: "Комплект с бриллиантами «9 go'zal»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 8.0,
    stones: "Бриллианты",
    images: ["images/products/tg-191-1.jpg", "images/products/tg-191-2.jpg", "images/products/tg-191-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «9 go'zal»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «9 go'zal»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 102,
    lot: 49,
    tg: 188,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.5,
    stones: "Бриллианты",
    images: ["images/products/tg-188-1.jpg", "images/products/tg-188-2.jpg", "images/products/tg-188-3.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 103,
    lot: 48,
    tg: 185,
    name: "Комплект с бриллиантами «Нежный»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 5.7,
    stones: "Бриллианты",
    images: ["images/products/tg-185-1.jpg", "images/products/tg-185-2.jpg", "images/products/tg-185-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Нежный»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Нежный»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 104,
    lot: 47,
    tg: 182,
    name: "Комплект с бриллиантами «Розочка»",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 8.2,
    stones: "Бриллианты",
    images: ["images/products/tg-182-1.jpg", "images/products/tg-182-2.jpg", "images/products/tg-182-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Розочка»",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Розочка»",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 105,
    lot: 46,
    tg: 179,
    name: "Комплект с бриллиантами «Виноград»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 4.9,
    stones: "Бриллианты",
    images: ["images/products/tg-179-1.jpg", "images/products/tg-179-2.jpg", "images/products/tg-179-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Виноград»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Виноград»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 106,
    lot: 45,
    tg: 176,
    name: "Комплект с бриллиантами «Бай хатын»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 11.45,
    stones: "Бриллианты",
    images: ["images/products/tg-176-1.jpg", "images/products/tg-176-2.jpg", "images/products/tg-176-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Бай хатын»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Бай хатын»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 107,
    lot: 44,
    tg: 173,
    name: "Комплект «Золотой»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 8.6,
    stones: "Цирконий",
    images: ["images/products/tg-173-1.jpg", "images/products/tg-173-2.jpg", "images/products/tg-173-3.jpg"],
    uz: {
      name: "To'plam «Золотой»",
      material: "585 probali oltin",
      stones: "Sirkoniy",
    },
    kaa: {
      name: "Komplekt «Золотой»",
      material: "585 probalı altın",
      stones: "Cirkoniy",
    },
  },
  {
    id: 108,
    lot: 43,
    tg: 170,
    name: "Комплект с бриллиантами «Салют»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 10.8,
    stones: "Бриллианты",
    images: ["images/products/tg-170-1.jpg", "images/products/tg-170-2.jpg", "images/products/tg-170-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Салют»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Салют»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 109,
    lot: 42,
    tg: 167,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.55,
    stones: "Бриллианты",
    images: ["images/products/tg-167-1.jpg", "images/products/tg-167-2.jpg", "images/products/tg-167-3.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 110,
    lot: 41,
    tg: 164,
    name: "Комплект с бриллиантами «Мадонна»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 7.5,
    stones: "Бриллианты",
    images: ["images/products/tg-164-1.jpg", "images/products/tg-164-2.jpg", "images/products/tg-164-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Мадонна»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Мадонна»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 111,
    lot: 40,
    tg: 161,
    name: "Комплект с бриллиантами «7 красавиц»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.45,
    stones: "Бриллианты",
    images: ["images/products/tg-161-1.jpg", "images/products/tg-161-2.jpg", "images/products/tg-161-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «7 красавиц»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «7 красавиц»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 112,
    lot: 39,
    tg: 158,
    name: "Комплект с бриллиантами «Бахчасарай квадрат»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 9.9,
    stones: "Бриллианты",
    images: ["images/products/tg-158-1.jpg", "images/products/tg-158-2.jpg", "images/products/tg-158-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Бахчасарай квадрат»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Бахчасарай квадрат»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 113,
    lot: 38,
    tg: 155,
    name: "Комплект с бриллиантами «Галстук»",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 9.75,
    stones: "Бриллианты",
    images: ["images/products/tg-155-1.jpg", "images/products/tg-155-2.jpg", "images/products/tg-155-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Галстук»",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Галстук»",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 114,
    lot: 37,
    tg: 152,
    name: "Комплект с бриллиантами «Большая розочка»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 8.6,
    stones: "Бриллианты",
    images: ["images/products/tg-152-1.jpg", "images/products/tg-152-2.jpg", "images/products/tg-152-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Большая розочка»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Большая розочка»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 115,
    lot: 36,
    tg: 149,
    name: "Комплект с бриллиантами «Чархпалак»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 6.3,
    stones: "Бриллианты",
    images: ["images/products/tg-149-1.jpg", "images/products/tg-149-2.jpg", "images/products/tg-149-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Чархпалак»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Чархпалак»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 116,
    lot: 35,
    tg: 146,
    name: "Комплект с бриллиантами «Бантик»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 10.0,
    stones: "Бриллианты",
    images: ["images/products/tg-146-1.jpg", "images/products/tg-146-2.jpg", "images/products/tg-146-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Бантик»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Бантик»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 117,
    lot: 34,
    tg: 143,
    name: "Комплект с бриллиантами «Вишня»",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 7.35,
    stones: "Бриллианты",
    images: ["images/products/tg-143-1.jpg", "images/products/tg-143-2.jpg", "images/products/tg-143-3.jpg"],
    uz: {
      name: "Brilliantli to'plam «Вишня»",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt «Вишня»",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 118,
    lot: 33,
    tg: 140,
    name: "Комплект с бриллиантами",
    category: "sets",
    price: null,
    material: "Золото 585",
    weight: 8.2,
    stones: "Бриллианты",
    images: ["images/products/tg-140-1.jpg", "images/products/tg-140-2.jpg", "images/products/tg-140-3.jpg"],
    uz: {
      name: "Brilliantli to'plam",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Brilliantlı komplekt",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 119,
    lot: 32,
    tg: 137,
    name: "Комплект «Поцелуй»",
    category: "sets",
    price: null,
    material: "Золото 583",
    weight: 9.0,
    images: ["images/products/tg-137-1.jpg", "images/products/tg-137-2.jpg", "images/products/tg-137-3.jpg"],
    uz: {
      name: "To'plam «Поцелуй»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Komplekt «Поцелуй»",
      material: "583 probalı altın",
    },
  },
  {
    id: 120,
    lot: 31,
    tg: 135,
    name: "Серьги «Шарик»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 1.2,
    images: ["images/products/tg-135-1.jpg", "images/products/tg-135-2.jpg"],
    uz: {
      name: "Sirg'alar «Шарик»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Шарик»",
      material: "583 probalı altın",
    },
  },
  {
    id: 121,
    lot: 30,
    tg: 133,
    name: "Серьги «Ромбик»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 1.2,
    images: ["images/products/tg-133-1.jpg", "images/products/tg-133-2.jpg"],
    uz: {
      name: "Sirg'alar «Ромбик»",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Ромбик»",
      material: "585 probalı altın",
    },
  },
  {
    id: 122,
    lot: 29,
    tg: 131,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 2.2,
    images: ["images/products/tg-131-1.jpg", "images/products/tg-131-2.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Sırǵalar",
      material: "585 probalı altın",
    },
  },
  {
    id: 123,
    lot: 28,
    tg: 129,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 3.9,
    stones: "Гранат",
    images: ["images/products/tg-129-1.jpg", "images/products/tg-129-2.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "583 probali oltin",
      stones: "Granat",
    },
    kaa: {
      name: "Sırǵalar",
      material: "583 probalı altın",
      stones: "Granat",
    },
  },
  {
    id: 124,
    lot: 27,
    tg: 127,
    name: "Серьги «Капуста»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 6.4,
    images: ["images/products/tg-127-1.jpg", "images/products/tg-127-2.jpg"],
    uz: {
      name: "Sirg'alar «Капуста»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Капуста»",
      material: "583 probalı altın",
    },
  },
  {
    id: 125,
    lot: 26,
    tg: 125,
    name: "Серьги «Висячие фионит»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 5.45,
    stones: "Фианит",
    images: ["images/products/tg-125-1.jpg", "images/products/tg-125-2.jpg"],
    uz: {
      name: "Sirg'alar «Висячие фионит»",
      material: "583 probali oltin",
      stones: "Fianit",
    },
    kaa: {
      name: "Sırǵalar «Висячие фионит»",
      material: "583 probalı altın",
      stones: "Fianit",
    },
  },
  {
    id: 126,
    lot: 25,
    tg: 123,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 3.75,
    images: ["images/products/tg-123-1.jpg", "images/products/tg-123-2.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar",
      material: "583 probalı altın",
    },
  },
  {
    id: 127,
    lot: 24,
    tg: 121,
    name: "Серьги «Труба»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 4.3,
    images: ["images/products/tg-121-1.jpg", "images/products/tg-121-2.jpg"],
    uz: {
      name: "Sirg'alar «Труба»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Труба»",
      material: "583 probalı altın",
    },
  },
  {
    id: 128,
    lot: 23,
    tg: 119,
    name: "Серьги «Подушка»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 4.6,
    images: ["images/products/tg-119-1.jpg", "images/products/tg-119-2.jpg"],
    uz: {
      name: "Sirg'alar «Подушка»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Подушка»",
      material: "583 probalı altın",
    },
  },
  {
    id: 129,
    lot: 22,
    tg: 117,
    name: "Серьги «Ромбик»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 3.3,
    images: ["images/products/tg-117-1.jpg", "images/products/tg-117-2.jpg"],
    uz: {
      name: "Sirg'alar «Ромбик»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Ромбик»",
      material: "583 probalı altın",
    },
  },
  {
    id: 130,
    lot: 21,
    tg: 115,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 5.5,
    stones: "Бриллианты",
    images: ["images/products/tg-115-1.jpg", "images/products/tg-115-2.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Sırǵalar",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 131,
    lot: 20,
    tg: 113,
    name: "Серьги «Неспелые гранаты»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 3.5,
    stones: "Гранат",
    images: ["images/products/tg-113-1.jpg", "images/products/tg-113-2.jpg"],
    uz: {
      name: "Sirg'alar «Неспелые гранаты»",
      material: "583 probali oltin",
      stones: "Granat",
    },
    kaa: {
      name: "Sırǵalar «Неспелые гранаты»",
      material: "583 probalı altın",
      stones: "Granat",
    },
  },
  {
    id: 132,
    lot: 19,
    tg: 111,
    name: "Серьги «Лунный камень»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 8.0,
    stones: "Лунный камень",
    images: ["images/products/tg-111-1.jpg", "images/products/tg-111-2.jpg"],
    uz: {
      name: "Sirg'alar «Лунный камень»",
      material: "583 probali oltin",
      stones: "Oy toshi",
    },
    kaa: {
      name: "Sırǵalar «Лунный камень»",
      material: "583 probalı altın",
      stones: "Ay tası",
    },
  },
  {
    id: 133,
    lot: 18,
    tg: 109,
    name: "Серьги «Бахча сарай»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 6.55,
    images: ["images/products/tg-109-1.jpg", "images/products/tg-109-2.jpg"],
    uz: {
      name: "Sirg'alar «Бахча сарай»",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Бахча сарай»",
      material: "585 probalı altın",
    },
  },
  {
    id: 134,
    lot: 17,
    tg: 107,
    name: "Серьги «Шарик»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 6.1,
    images: ["images/products/tg-107-1.jpg", "images/products/tg-107-2.jpg"],
    uz: {
      name: "Sirg'alar «Шарик»",
      material: "585 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Шарик»",
      material: "585 probalı altın",
    },
  },
  {
    id: 135,
    lot: 16,
    tg: 105,
    name: "Серьги «Фионит»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 4.8,
    stones: "Фианит",
    images: ["images/products/tg-105-1.jpg", "images/products/tg-105-2.jpg"],
    uz: {
      name: "Sirg'alar «Фионит»",
      material: "585 probali oltin",
      stones: "Fianit",
    },
    kaa: {
      name: "Sırǵalar «Фионит»",
      material: "585 probalı altın",
      stones: "Fianit",
    },
  },
  {
    id: 136,
    lot: 15,
    tg: 102,
    name: "Серьги «Поцелуй детский»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 1.0,
    images: ["images/products/tg-102-1.jpg", "images/products/tg-102-2.jpg"],
    uz: {
      name: "Sirg'alar «Поцелуй детский»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Поцелуй детский»",
      material: "583 probalı altın",
    },
  },
  {
    id: 137,
    lot: 14,
    tg: 100,
    name: "Серьги «Рубин»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 2.75,
    stones: "Рубин",
    images: ["images/products/tg-100-1.jpg", "images/products/tg-100-2.jpg"],
    uz: {
      name: "Sirg'alar «Рубин»",
      material: "583 probali oltin",
      stones: "Yoqut",
    },
    kaa: {
      name: "Sırǵalar «Рубин»",
      material: "583 probalı altın",
      stones: "Yaqut",
    },
  },
  {
    id: 138,
    lot: 13,
    tg: 98,
    name: "Серьги «Груша»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 2.5,
    images: ["images/products/tg-98-1.jpg", "images/products/tg-98-2.jpg"],
    uz: {
      name: "Sirg'alar «Груша»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Груша»",
      material: "583 probalı altın",
    },
  },
  {
    id: 139,
    lot: 12,
    tg: 96,
    name: "Серьги «Александрит»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 3.86,
    stones: "Александрит",
    images: ["images/products/tg-96-1.jpg", "images/products/tg-96-2.jpg"],
    uz: {
      name: "Sirg'alar «Александрит»",
      material: "583 probali oltin",
      stones: "Aleksandrit",
    },
    kaa: {
      name: "Sırǵalar «Александрит»",
      material: "583 probalı altın",
      stones: "Aleksandrit",
    },
  },
  {
    id: 140,
    lot: 11,
    tg: 94,
    name: "Серьги «Фионит-розочка»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 6.0,
    stones: "Фианит",
    images: ["images/products/tg-94-1.jpg", "images/products/tg-94-2.jpg"],
    uz: {
      name: "Sirg'alar «Фионит-розочка»",
      material: "585 probali oltin",
      stones: "Fianit",
    },
    kaa: {
      name: "Sırǵalar «Фионит-розочка»",
      material: "585 probalı altın",
      stones: "Fianit",
    },
  },
  {
    id: 141,
    lot: 10,
    tg: 92,
    name: "Серьги «Бирюза»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 4.3,
    stones: "Бирюза",
    images: ["images/products/tg-92-1.jpg", "images/products/tg-92-2.jpg"],
    uz: {
      name: "Sirg'alar «Бирюза»",
      material: "583 probali oltin",
      stones: "Feruza",
    },
    kaa: {
      name: "Sırǵalar «Бирюза»",
      material: "583 probalı altın",
      stones: "Piruza",
    },
  },
  {
    id: 142,
    lot: 9,
    tg: 90,
    name: "Серьги «Бирюза»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 5.0,
    stones: "Бирюза",
    images: ["images/products/tg-90-1.jpg", "images/products/tg-90-2.jpg"],
    uz: {
      name: "Sirg'alar «Бирюза»",
      material: "585 probali oltin",
      stones: "Feruza",
    },
    kaa: {
      name: "Sırǵalar «Бирюза»",
      material: "585 probalı altın",
      stones: "Piruza",
    },
  },
  {
    id: 143,
    lot: 8,
    tg: 88,
    name: "Серьги «Бирюза»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 5.4,
    stones: "Бирюза",
    images: ["images/products/tg-88-1.jpg", "images/products/tg-88-2.jpg"],
    uz: {
      name: "Sirg'alar «Бирюза»",
      material: "583 probali oltin",
      stones: "Feruza",
    },
    kaa: {
      name: "Sırǵalar «Бирюза»",
      material: "583 probalı altın",
      stones: "Piruza",
    },
  },
  {
    id: 144,
    lot: 7,
    tg: 86,
    name: "Серьги «Бирюза»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 5.1,
    stones: "Бирюза",
    images: ["images/products/tg-86-1.jpg", "images/products/tg-86-2.jpg"],
    uz: {
      name: "Sirg'alar «Бирюза»",
      material: "583 probali oltin",
      stones: "Feruza",
    },
    kaa: {
      name: "Sırǵalar «Бирюза»",
      material: "583 probalı altın",
      stones: "Piruza",
    },
  },
  {
    id: 145,
    lot: 6,
    tg: 84,
    name: "Серьги «Жалпак»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 5.0,
    images: ["images/products/tg-84-1.jpg", "images/products/tg-84-2.jpg"],
    uz: {
      name: "Sirg'alar «Жалпак»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Жалпак»",
      material: "583 probalı altın",
    },
  },
  {
    id: 146,
    lot: 5,
    tg: 82,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 8.5,
    stones: "Бриллианты",
    images: ["images/products/tg-82-1.jpg", "images/products/tg-82-2.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "583 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Sırǵalar",
      material: "583 probalı altın",
      stones: "Brilliantlar",
    },
  },
  {
    id: 147,
    lot: 4,
    tg: 80,
    name: "Серьги «Семья»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 5.65,
    stones: "Цветные камни",
    images: ["images/products/tg-80-1.jpg", "images/products/tg-80-2.jpg"],
    uz: {
      name: "Sirg'alar «Семья»",
      material: "585 probali oltin",
      stones: "Rangli toshlar",
    },
    kaa: {
      name: "Sırǵalar «Семья»",
      material: "585 probalı altın",
      stones: "Reńli taslar",
    },
  },
  {
    id: 148,
    lot: 3,
    tg: 78,
    name: "Серьги «Семья»",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 5.3,
    stones: "Цветные камни",
    images: ["images/products/tg-78-1.jpg", "images/products/tg-78-2.jpg"],
    uz: {
      name: "Sirg'alar «Семья»",
      material: "585 probali oltin",
      stones: "Rangli toshlar",
    },
    kaa: {
      name: "Sırǵalar «Семья»",
      material: "585 probalı altın",
      stones: "Reńli taslar",
    },
  },
  {
    id: 149,
    lot: 2,
    tg: 76,
    name: "Серьги «Жалпак»",
    category: "earrings",
    price: null,
    material: "Золото 583",
    weight: 5.35,
    images: ["images/products/tg-76-1.jpg", "images/products/tg-76-2.jpg"],
    uz: {
      name: "Sirg'alar «Жалпак»",
      material: "583 probali oltin",
    },
    kaa: {
      name: "Sırǵalar «Жалпак»",
      material: "583 probalı altın",
    },
  },
  {
    id: 150,
    lot: 1,
    tg: 74,
    name: "Серьги",
    category: "earrings",
    price: null,
    material: "Золото 585",
    weight: 5.5,
    stones: "Бриллианты",
    images: ["images/products/tg-74-1.jpg", "images/products/tg-74-2.jpg"],
    uz: {
      name: "Sirg'alar",
      material: "585 probali oltin",
      stones: "Brilliantlar",
    },
    kaa: {
      name: "Sırǵalar",
      material: "585 probalı altın",
      stones: "Brilliantlar",
    },
  },
];
